# Generated by Django 5.1.6 on 2025-03-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quote', models.IntegerField(max_length=100)),
                ('profit', models.FloatField(max_length=100)),
                ('rate', models.IntegerField(max_length=100)),
                ('qty', models.IntegerField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
    ]
