# Generated by Django 5.1.6 on 2025-03-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='process',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='process',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='process',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='process',
            name='rate',
        ),
    ]
