# Generated by Django 5.1.6 on 2025-03-07 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.action'),
        ),
        migrations.DeleteModel(
            name='process',
        ),
    ]
