# Generated by Django 5.1.6 on 2025-03-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_action_alter_price_description_delete_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.action')),
            ],
        ),
        migrations.DeleteModel(
            name='price',
        ),
    ]
